workflows:
  ios-release:
    name: iOS App Store Release
    max_build_duration: 60
    integrations:
      app_store_connect: Codemagic PORD Toximetro
    environment:
      flutter: stable
      xcode: latest
      - name: Get Flutter packages
        script: flutter pub get
      - name: Install pods
        script: |
          cd ios
          pod install
          cd ..
      - name: Set Development Team ID
        script: |
          sed -i '' 's/DEVELOPMENT_TEAM = ""/DEVELOPMENT_TEAM = P7L343G9G5/g' ios/Runner.xcodeproj/project.pbxproj
          sed -i '' 's/DEVELOPMENT_TEAM = ;/DEVELOPMENT_TEAM = P7L343G9G5;/g' ios/Runner.xcodeproj/project.pbxproj
                - name: Create Export Options
        script: |
          cat > $HOME/export_options.plist << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>teamID</key>
              <string>P7L343G9G5</string>
              <key>method</key>
              <string>app-store</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>signingCertificate</key>
              <string>Apple Distribution</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>com.toximetro.ios</key>
                  <string>Toximetro App Store Profile</string>
              </dict>
          </dict>
          </plist>
          EOF
      - name: Build IPA
        script: flutter build ipa --release --export-options-plist=$HOME/export_options.plist    artifacts:
      - build/ios/ipa/*.ipa
