workflows:
  ios-release:
    name: iOS App Store Release
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Install pods
        script: |
          cd ios
          pod install
          cd ..
              - name: Create ExportOptions.plist
                    script: |
                            cat > ios/ExportOptions.plist << 'EOF'
                                    <?xml version="1.0" encoding="UTF-8"?>
                                            <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
                                                    <plist version="1.0">
                                                            <dict>
                                                                        <key>method</key>
                                                                                    <string>app-store</string>
                                                                                                <key>signingStyle</key>
                                                                                                            <string>automatic</string>
                                                                                                                    </dict>
                                                                                                                            </plist>
                                                                                                                                    EOF
      - name: Build IPA
        script: flutter build ipa --release --export-options-plist=ios/ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
