workflows:
  ios-release:
    name: iOS App Store Release
    max_build_duration: 60

    integrations:
      app_store_connect: Codemagic PROD Toximetro

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Install pods
        script: |
          cd ios
          pod install

      - name: Build IPA
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
