workflows:
  ios-release:
    name: iOS App Store Release
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Install pods
        script: |
          cd ios
          pod install
          cd ..
              - name: Setup code signing
      script: |
        cat > /tmp/export_options.plist << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
          <key>method</key>
          <string>app-store</string>
          <key>teamID</key>
          <string>P7L343G9G5</string>
          <key>uploadSymbols</key>
          <true/>
          <key>uploadBitcode</key>
          <false/>
        </dict>
        </plist>
        EOF

      - name: Build IPA
        script: flutter build ipa --release --export-options-plist=/tmp/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
