workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build iOS IPA
        script: |
          flutter build ipa --release --flavor ios-production -t lib/main_prod.dart
    artifacts:
      - build/ios/ipa/*.ipa

  android-workflow:
    name: Android Workflow  
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build Android AAB
        script: |
          flutter build appbundle --release --flavor android-production -t lib/main_prod.dart
    artifacts:
      - build/**/outputs/**/*.aab
